### ISSUE TITLE
nix-shell

### ISSUE THREAD

**Issue by PFC-developer** [SiennaNetwork/SiennaNetwork#1]
it looks like shell.nix is expecting an older version of https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz
and it's sha has changed.

(or nixpkgs-mozilla has been hacked)

**Comment by mradkov** [comment]
The sha has changed because of update in mozila packages, you can replace it with the current one.

**Comment by mradkov** [comment]
closing this because of no further activity.
